version: '3'

services:
  surrealdb:
    image: surrealdb/surrealdb:v1.0.1
    container_name: surrealdb
    command: start --user surrealdb --pass surrealdb 
    ports:
      - 8000:8000
    volumes:
      - volume-surrealdb:/data
  

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - volume-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres


volumes:
  volume-surrealdb:
   driver: local
  volume-postgres:  
   driver: local